name: VercelBar
options:
  bundleIdPrefix: com.example
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    SWIFT_VERSION: 5.9
    VERCEL_CLIENT_ID: $(VERCEL_CLIENT_ID)
    VERCEL_CLIENT_SECRET: $(VERCEL_CLIENT_SECRET)
    VERCEL_REDIRECT_URI: $(VERCEL_REDIRECT_URI)
    VERCEL_SCOPES: $(VERCEL_SCOPES)
    SPARKLE_FEED_URL: $(SPARKLE_FEED_URL)
    SPARKLE_PUBLIC_ED_KEY: $(SPARKLE_PUBLIC_ED_KEY)

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle.git
    from: 2.7.0

schemes:
  VercelBar:
    build:
      targets:
        VercelBar: all
    test:
      targets:
        - VercelBarTests

targets:
  VercelBar:
    type: application
    platform: macOS
    sources:
      - App
      - Features
      - Core
      - path: Resources
        buildPhase: resources
    info:
      path: App/Info.plist
      properties:
        ATSApplicationFontsPath: Fonts
        LSUIElement: true
        SUEnableAutomaticChecks: true
        SUFeedURL: $(SPARKLE_FEED_URL)
        SUPublicEDKey: $(SPARKLE_PUBLIC_ED_KEY)
        CFBundleURLTypes:
          - CFBundleURLName: com.example.VercelBar
            CFBundleURLSchemes:
              - vercelbar
        VercelClientId: $(VERCEL_CLIENT_ID)
        VercelClientSecret: $(VERCEL_CLIENT_SECRET)
        VercelRedirectURI: $(VERCEL_REDIRECT_URI)
        VercelScopes: $(VERCEL_SCOPES)
    configFiles:
      Debug: Config/Secrets.xcconfig
      Release: Config/Secrets.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.VercelBar
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: Sparkle
        product: Sparkle
  VercelBarTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: VercelBar
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.example.VercelBarTests
